### ISSUE TITLE
regarding a storing a data in nv memory of tpm , without using authorisation or key storing techniques. 

### ISSUE THREAD

**Issue by manojsai17** [stefanberger/libtpms#13]
Hello,

actually main problem is we interfaced slb 9670(tpm-2.0) with 16 bit msp430 controller which does not support linux kernel or any OS.

now our task is to store a 100 byes of data in NV memory, without any authorisation technique, as simple as possible.

please guide me in that way.

slb 9670 is interfaced with msp430 controller through SPI protocol.

I able to read device id , version id of slb9670 , so spi communication is working fine with our controller .

what is packet format to be send with our data , i am not able to understand the TCG documents .

theoretically iam able to understand we have to do nvdefinespace , nvwrite ,nvread .. internaly what is the format i have to be send not able to understand

can you please guide me , or share any code snippet .

sorry if i trouble you or any irrelevant questions.

Regards,
Manoj,
mail : abbarajumanojsai@gmail.com
+91-9063249308

**Comment by stefanberger** [comment]
My suggestion would be to start with Linux on Fedora for example and install the [IBM TSS stack and client tools](https://fedora.pkgs.org/27/fedora-x86_64/tss2-713-7.fc26.x86_64.rpm.html) and use its tssnv* tools with a hardware TPM 2 (or TPM 2 simulator or virtual TPM) and pass the -v parameter on the command line, which then displays the byte sequences sent to the TPM2. You can then learn the sequences you would need to send in your case.

I am going to close your issue since it is not libtpms related.
