### ISSUE TITLE
nvi in USER_NVRAM_Unmarshal() used without initialization?

### ISSUE THREAD

**Issue by setharnold** [stefanberger/libtpms#310]
https://github.com/stefanberger/libtpms/blob/8590849b65260d71d22e5509f0c3ba44079cf780/src/tpm2/NVMarshal.c#L4666

Hello, Coverity has flagged function `USER_NVRAM_Unmarshal()` in `src/tpm2/NVMarshal.c` as using the `nvi` variable without initializing it; perhaps I'm missing some context, but it does appear that `nvi` is passed to `NV_INDEX_Unmarshal()` before it is initialized, and `NV_INDEX_Unmarshal()` performs `&data->publicArea` without itself initializing `*data`.

Thanks

**Comment by stefanberger** [comment]
I have the same explanation as for #310. Garbage read from fields of uninitialized structure and the same garbage possibly written back to the field it was read from  have no negative side effects. We can initialize the variable to keep Coverity happy/quiet...

I have 'some' issues reported to me by Coverity. Some are odd 'cut and paste error' reports due to variables with similar name. These are false positives. Others are also not making sense, either. I clicked them all away with false positives but maybe you find something.
