### ISSUE TITLE
RFE: SGX enclave support

### ISSUE THREAD

**Issue by DemiMarie** [stefanberger/libtpms#365]
By running libtpms in an SGX enclave, secrets stored in the TPM can be protected from extraction by a compromised host process.

**Comment by stefanberger** [comment]
Which application would you want to link with libtpms to use it in an SGX encalve? swtpm + libtpms for example runs in an SGX enclave using Gramine, which is good since it avoids having to natively support for swtpm for SGX enclaves as well. I think swtpm under Gramine is a sufficient solution. If you have another application in mind let me know. PRs demonstrating what it takes to run them natively in an SGX environment are welcome.

**Comment by DemiMarie** [comment]
> Which application would you want to link with libtpms to use it in an SGX encalve?

I was thinking of having QEMU or rust-vmm run libtpms in an enclave embedded in the userspace VMM.  This would avoid having to spawn a separate process.

**Comment by stefanberger** [comment]
> I was thinking of having QEMU or rust-vmm run libtpms in an enclave embedded in the userspace VMM. This would avoid having to spawn a separate process.

QEMU is not linking with libtpms and will never do that but uses TPM via swptm. I am not involved in rust-vmm but as I said I am open to looking at otehes' PRs.

**Comment by stefanberger** [comment]
It looks like rust-vmm is also using swtpm as the backend: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/tpm.md
Does this RFE have a real 'need'?

**Comment by DemiMarie** [comment]
Not really, closing.
