### ISSUE TITLE
libnss3-dev 3.17.2 dependent on ubuntu

### ISSUE THREAD

**Issue by Kailiangying** [stefanberger/libtpms#4]
Hi, 

I notice the libtpms on ubuntu depend on libnss3-dev 3.17.2. Could anyone provide some guideline how to download this specific version of library on ubuntu? 

Thanks in advance

**Comment by stefanberger** [comment]
Older versions of libnss3-dev are missing blapi.h. The version in Ubuntu Vivid or later releases of Ubuntu has this file: 

http://packages.ubuntu.com/vivid/amd64/libnss3-dev/filelist

The file seems to be missing in trusty:

http://packages.ubuntu.com/trusty/amd64/libnss3-dev/filelist

If you are on Vivid or a more recent version of Ubuntu, you should be able to install the right version of libnss3-dev. If you are buliding from source you can also use openssl as the crypto library. Run the following steps:

./bootstrap.sh
./configure --prefix=/usr --with-openssl
make
sudo make install

I hope this helps.

**Comment by yingkailiang** [comment]
Hi, @stefanberger. Thanks for your detail explain. 
I have tried to set up libtpms on Ubuntu vivid. Using the command you provide, I can success install libtpms. I also plan to setup swtpm. 
Just to report have I found when I still use ./configure --prefix=/usr in libtpms, following the error message I got on vivid with all dependent libraries installed. 

`error: "Could not find AES_CreateContext(). Is nss-softokn-freebl-devel/libnss3-dev installed?`

Because I also got the same error message when I try to setup swtpm. The libnss version I installed is 3.19.2. 
Do you have suggestion how to overcome this error when I set up swtpm? 
Thanks in advance.

**Comment by yingkailiang** [comment]
I try the same set of command you provide to compile the swtpm. I can pass the ./configure -prefix=/usr --with-openssl. Following the compile error I got when I make the project.
![error](https://cloud.githubusercontent.com/assets/3341468/14535204/bb4dfa14-023a-11e6-9acd-6be31c0ce6f7.png)

**Comment by stefanberger** [comment]
I pushed an update that fixes this problem. Thanks for trying.

**Comment by Kailiangying** [comment]
thanks for your quick response today. I have set up the swtpm properly. I will start hacking into vTPM.
